# -*- coding: utf-8 -*-
"""ybi task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2SmM7VLxvkAktum4MN96ijyEh6xKfuH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("https://github.com/ybifoundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv")

df.head()

df.describe()

df.info()

df.isnull().sum()

import seaborn as sns
corr=df.corr()
plt.figure(figsize=(10,9))
sns.heatmap(corr,annot=True)
plt.show()

df.columns

sns.pairplot(df, diag_kind='kde')

df.hist(figsize=(15,15))

y=df["Concrete Compressive Strength(MPa, megapascals) "]
y.shape

x=df.drop("Concrete Compressive Strength(MPa, megapascals) ",axis=1)
x.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40,random_state=0)
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

model.score(x_test,y_test)

from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test,y_pred))